#include "Console.h"

#include "BmpImage.h"
#include "MpAssets.h"

#include "../mp_core/KeyboardLayout.h"

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <set>
#include <tuple>

namespace mp::ui {
namespace {

// Hauptwerk installs artwork exactly like audio: under
// OrganInstallationPackages/<id zero-padded to six digits>. Bitmap filenames
// are frequently written with a leading slash ("/Images/Numbers/Number0.png"),
// which is relative to the package, not to the filesystem root.
std::filesystem::path resolveBitmap(const std::string& rootDir,
                                    const std::string& fileName, Id packageId) {
  std::string rel = fileName;
  std::replace(rel.begin(), rel.end(), '\\', '/');
  while (!rel.empty() && rel.front() == '/') rel.erase(rel.begin());

  std::filesystem::path base(rootDir);
  if (packageId > 0) {
    std::string digits = std::to_string(packageId);
    if (digits.size() < 6) digits.insert(0, 6 - digits.size(), '0');
    base /= "OrganInstallationPackages";
    base /= digits;
  }
  return base / rel;
}

// One of Masterpiece's own wood tiles, for a texture from "Hauptwerk Standard
// Components" that is not here. Those are named like "SeamlessWoodBkgnds -
// VGrain011": the grain direction is in the name, and the number picks one of
// eight tones so neighbouring panels are not all the same wood. The tiles are
// generated by tools/gen-wood.py and embedded in the build.
juce::Image woodTileFor(const std::string& name) {
  const juce::String n(name);
  const bool vertical = n.containsIgnoreCase("VGrain");
  const int number = n.retainCharacters("0123456789").getTrailingIntValue();
  const int tone = ((number > 0 ? number - 1 : 0) % 8) + 1;
  const juce::String resource = juce::String("wood") + (vertical ? "v" : "h") +
                                juce::String(tone).paddedLeft('0', 2) + "_png";
  int size = 0;
  if (const char* data = MpAssets::getNamedResource(resource.toRawUTF8(), size))
    return juce::ImageFileFormat::loadFrom(data, static_cast<size_t>(size));
  return {};
}

// Windows-authored sets record whatever case the author used; Linux does not
// forgive it. Same fallback the sample loader needs, for the same reason.
std::filesystem::path resolveIgnoringCase(const std::filesystem::path& wanted) {
  std::error_code ec;
  if (std::filesystem::exists(wanted, ec)) return wanted;
  const auto dir = wanted.parent_path();
  if (!std::filesystem::is_directory(dir, ec)) return wanted;

  std::string target = wanted.filename().string();
  std::transform(target.begin(), target.end(), target.begin(),
                 [](unsigned char c) { return std::tolower(c); });
  for (const auto& entry : std::filesystem::directory_iterator(dir, ec)) {
    std::string have = entry.path().filename().string();
    std::transform(have.begin(), have.end(), have.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    if (have == target) return entry.path();
  }
  return wanted;
}

constexpr int64_t cacheKey(Id setId, int index) {
  return (static_cast<int64_t>(setId) << 20) ^ static_cast<int64_t>(index);
}

} // namespace

ConsoleView::ConsoleView(MasterpieceProcessor& p) : proc_(p) { rebuild(); }

void ConsoleView::rebuild() {
  items_.clear();
  texts_.clear();
  keys_.clear();
  drawnKeys_.clear();
  heldKey_ = -1;
  pageIds_.clear();
  cache_.clear();
  hasArtwork_ = false;
  extent_ = {};
  organRoot_ = proc_.organRootDir();

  const auto& model = proc_.organModel();

  // Which switch owns which drawn instance. Built once here rather than
  // searched per item: Nancy has 7983 switches.
  std::unordered_map<Id, const Switch*> switchByInstance;
  for (const auto& [id, sw] : model.switches) {
    (void)id;
    if (sw.dispInstanceId != 0) switchByInstance[sw.dispInstanceId] = &sw;
  }

  // And which continuous control owns which. An organ declares a control for
  // every level and every detuning parameter and draws only the handful it
  // means you to touch: Nancy has 1420 and draws 55.
  std::unordered_map<Id, const ContinuousControl*> controlByInstance;
  for (const auto& [id, c] : model.continuousControls) {
    (void)id;
    if (c.imageSetInstanceId != 0) controlByInstance[c.imageSetInstanceId] = &c;
  }

  for (const auto& [pageId, page] : model.displayPages) {
    (void)page;
    pageIds_.push_back(pageId);
  }
  std::sort(pageIds_.begin(), pageIds_.end());
  if (pageIndex_ >= static_cast<int>(pageIds_.size())) pageIndex_ = 0;
  if (pageIds_.empty()) return;

  const Id showing = pageIds_[static_cast<size_t>(pageIndex_)];
  const auto pageIt = model.displayPages.find(showing);
  if (pageIt == model.displayPages.end()) return;

  for (const auto& inst : pageIt->second.instances) {
    const auto setIt = model.imageSets.find(inst.imageSetFor(layout_));
    if (setIt == model.imageSets.end()) continue;

    Item item;
    item.instanceId = inst.instanceId;
    item.imageSetId = inst.imageSetFor(layout_);
    item.defaultIndex = inst.defaultImageIndex > 0 ? inst.defaultImageIndex : 1;
    item.layer = inst.layer;

    const auto sit = switchByInstance.find(inst.instanceId);

    // A drawn switch that the organ declares to be a KEY is not a drawstop.
    // Sets whose manuals are part of a photographed backdrop draw every key
    // this way; treating them as drawstops makes a manual that toggles
    // pictures and sounds nothing.
    if (sit != switchByInstance.end()) {
      const auto kk = model.keyboardKeys.find(sit->second->switchId);
      if (kk != model.keyboardKeys.end()) {
        KeyItem key;
        key.midiNote = kk->second.midiNote;
        key.channel = proc_.channelForKeyboard(kk->second.keyboardId);
        key.imageSetId = inst.imageSetFor(layout_);
        key.engagedIndex = sit->second->dispIndexEngaged;
        key.disengagedIndex = sit->second->dispIndexDisengaged;
        const int kw = setIt->second.widthPx;
        const int kh = setIt->second.heightPx;
        key.bounds = {inst.leftFor(layout_), inst.topFor(layout_),
                      kw > 0 ? kw : 12, kh > 0 ? kh : 60};
        if (kw <= 0 || kh <= 0)
          if (const juce::Image* img =
                  imageFor(key.imageSetId, key.disengagedIndex)) {
            key.bounds.setWidth(img->getWidth());
            key.bounds.setHeight(img->getHeight());
          }
        // Sharps are drawn over naturals and are the narrower of the two, so
        // the narrow ones have to be hit-tested first.
        key.sharp = isSharpPitchClass(pitchClassOf(key.midiNote));
        extent_ = extent_.getUnion(key.bounds);
        drawnKeys_.push_back(key);
        continue;
      }
    }

    if (sit != switchByInstance.end()) {
      item.switchId = sit->second->switchId;
      item.engagedIndex = sit->second->dispIndexEngaged;
      item.disengagedIndex = sit->second->dispIndexDisengaged;
      item.clickable = sit->second->clickable;
    }

    if (const auto cit = controlByInstance.find(inst.instanceId);
        cit != controlByInstance.end()) {
      item.controlId = cit->second->controlId;
      item.clickable = cit->second->clickable;
      item.controlHigherIsMore = cit->second->clickingHigherIncreasesValue;
    }

    // The set knows the frame size; the instance knows where it goes, and
    // whether it repeats to fill a larger rectangle.
    int w = setIt->second.widthPx;
    int h = setIt->second.heightPx;
    const int left = inst.leftFor(layout_);
    const int top = inst.topFor(layout_);
    // Most sets declare no size at all and let the bitmap say. Falling back to
    // a fixed box instead made a drawstop clickable only in its top-left
    // corner, so clicking the knob did nothing — which looked exactly like a
    // coupler that was not wired up.
    if ((w <= 0 || h <= 0) && !inst.tilesFor(layout_)) {
      if (const juce::Image* img = imageFor(item.imageSetId, item.defaultIndex)) {
        w = img->getWidth();
        h = img->getHeight();
      } else if (setIt->second.clickRightPx > 0 && setIt->second.clickBottomPx > 0) {
        // No size declared and no picture to measure -- the images live in a
        // package that is not installed. The clickable area is the next best
        // measure of the control: a list item on Hajós is a 152x14 strip, and
        // the fixed box below made every one of them a 32x32 square piled on
        // its neighbours.
        w = setIt->second.clickRightPx;
        h = setIt->second.clickBottomPx;
      }
    }
    if (inst.tilesFor(layout_)) {
      item.tiled = true;
      item.bounds = {left, top, inst.tileRightFor(layout_) - left,
                     inst.tileBottomFor(layout_) - top};
    } else {
      item.bounds = {left, top, w > 0 ? w : 32, h > 0 ? h : 32};
    }

    // The organ may name a smaller live area inside the picture.
    item.hitBounds = item.bounds;
    if (setIt->second.hasClickArea() && !item.tiled) {
      const auto& set = setIt->second;
      item.hitBounds = juce::Rectangle<int>(
          left + set.clickLeftPx, top + set.clickTopPx,
          set.clickRightPx - set.clickLeftPx,
          set.clickBottomPx - set.clickTopPx);
    }

    extent_ = extent_.getUnion(item.bounds);
    items_.push_back(item);
  }

  // ScreenLayerNumber is paint order: low layers are the backdrop, high layers
  // the controls sitting on top of it. stable_sort so instances that share a
  // layer keep their file order, which is how overlapping artwork is authored.
  std::stable_sort(items_.begin(), items_.end(),
                   [](const Item& a, const Item& b) { return a.layer < b.layer; });

  // Keys that came from drawn switches go in front of the assembled ones, and
  // the sharps in front of those, so a click lands on the narrowest thing
  // under it.
  for (const auto& k : drawnKeys_)
    if (!k.sharp) keys_.push_back(k);
  for (const auto& k : drawnKeys_)
    if (k.sharp) keys_.push_back(k);
  drawnKeys_.clear();

  buildKeyboards(model, showing);
  buildTexts(model, showing);
  for (const auto& k : keys_) extent_ = extent_.getUnion(k.bounds);

  // How many layouts this organ offers. A set with one console size declares
  // no alternates at all, which is most of them.
  layoutCount_ = 1;
  for (const auto& [pid, page] : model.displayPages) {
    (void)pid;
    for (const auto& inst : page.instances)
      for (int a = 3; a >= 1; --a)
        if (inst.hasLayout(a)) layoutCount_ = std::max(layoutCount_, a + 1);
  }
  if (layout_ >= layoutCount_) layout_ = 0;

  hasArtwork_ = !items_.empty() || !keys_.empty() || !texts_.empty();
  setSize(std::max(extent_.getRight(), 320), std::max(extent_.getBottom(), 240));

  // Only poll while there is something on screen whose picture can change
  // under the player's hands.
  if (!keys_.empty())
    startTimerHz(30);
  else
    stopTimer();
}

void ConsoleView::buildTexts(const OrganModel& model, Id pageId) {
  const auto pageIt = model.displayPages.find(pageId);
  if (pageIt == model.displayPages.end()) return;

  // Text can be positioned relative to a drawn thing, so the instances of
  // this page have to be reachable by id.
  std::unordered_map<Id, const ImageSetInstance*> byId;
  for (const auto& inst : pageIt->second.instances)
    byId[inst.instanceId] = &inst;

  for (const auto& t : pageIt->second.texts) {
    if (t.text.empty()) continue;

    // A missing style is not a missing label: Hauptwerk's defaults are
    // Arial 10, normal weight, black, centred across its position.
    TextStyle style;
    if (const auto sit = model.textStyles.find(t.styleId);
        sit != model.textStyles.end())
      style = sit->second;

    TextItem item;
    item.text = juce::String::fromUTF8(t.text.c_str());
    // The set names a Windows, a Mac and a Linux face for the same style.
    // Whichever this machine has is the one the engraver meant; JUCE falls
    // back to the default face when none of them is installed.
    juce::String face = juce::String::fromUTF8(style.faceWindows.c_str());
   #if JUCE_MAC
    if (!style.faceMac.empty()) face = juce::String::fromUTF8(style.faceMac.c_str());
   #elif JUCE_LINUX
    if (!style.faceLinux.empty()) face = juce::String::fromUTF8(style.faceLinux.c_str());
   #endif
    if (face.isEmpty()) face = "Arial";
    // Font_SizePixels is a height in pixels, which is what JUCE wants.
    const float height = static_cast<float>(style.sizePx > 0 ? style.sizePx : 10);
    int flags = juce::Font::plain;
    if (style.weightCode >= 3) flags |= juce::Font::bold;
    if (style.italic) flags |= juce::Font::italic;
    if (style.underline) flags |= juce::Font::underlined;
    item.font = juce::Font(juce::FontOptions(face, height, flags));
    item.colour = juce::Colour(static_cast<juce::uint8>(style.red),
                               static_cast<juce::uint8>(style.green),
                               static_cast<juce::uint8>(style.blue));

    // The position is an anchor, and the alignment codes say which part of
    // the text sits on it.
    int x = t.xPx;
    int y = t.yPx;
    if (t.attachedInstanceId != 0 && t.posRelativeToInstance) {
      const auto ait = byId.find(t.attachedInstanceId);
      if (ait != byId.end()) {
        x += ait->second->leftFor(layout_);
        y += ait->second->topFor(layout_);
      }
    }

    const bool centred = style.hAlignCode == 0 || style.hAlignCode == 3;
    const bool rightAligned = style.hAlignCode == 2;
    // XPosPixels and YPosPixels are the top-left corner of the text's box,
    // not the middle of the text: the alignment codes place the string INSIDE
    // that box. Treating the position as a centre anchor pulled every label
    // half its own width to the left, which is how this was first written.
    //
    // The box is declared only for wrapped text, so when there is none the
    // string is measured and the alignment has nothing to move it within.
    int w = t.boxWidthPx;
    int h = t.boxHeightPx;
    item.wrap = w > 0 && h > 0;
    if (!item.wrap) {
      w = juce::GlyphArrangement::getStringWidthInt(item.font, item.text) + 2;
      h = static_cast<int>(std::ceil(item.font.getHeight()));
    }

    const int horizontal = centred ? juce::Justification::horizontallyCentred
                           : rightAligned ? juce::Justification::right
                                          : juce::Justification::left;
    const int vertical = style.vAlignCode == 0 ? juce::Justification::verticallyCentred
                         : style.vAlignCode == 2 ? juce::Justification::bottom
                                                 : juce::Justification::top;
    item.justification = juce::Justification(horizontal | vertical);
    item.bounds = {x, y, w, h};
    extent_ = extent_.getUnion(item.bounds);
    texts_.push_back(std::move(item));
  }
}

void ConsoleView::buildKeyboards(const OrganModel& model, Id pageId) {
  // Sharps are collected separately and appended, so they paint over the
  // naturals they overlap and are hit-tested before them.
  std::vector<KeyItem> sharps;

  // Hauptwerk models the player's keys and the organ's keys as two separate
  // Keyboard rows drawn in exactly the same place: one accessible for input,
  // one for output. Drawing both would stack two identical manuals and make
  // every click ambiguous, so the second one is dropped. Identity is the
  // drawn geometry, not the name, which is set-specific.
  std::set<std::tuple<Id, int, int, int, int>> alreadyDrawn;

  // A keyboard is laid out in a stable order so which of a duplicated pair
  // wins does not depend on the hash table's iteration order.
  std::vector<const Keyboard*> ordered;
  ordered.reserve(model.keyboards.size());
  for (const auto& [kbId, kb] : model.keyboards) {
    (void)kbId;
    ordered.push_back(&kb);
  }
  std::sort(ordered.begin(), ordered.end(),
            [](const Keyboard* a, const Keyboard* b) {
              return a->keyboardId < b->keyboardId;
            });

  for (const Keyboard* kbp : ordered) {
    const Keyboard& kb = *kbp;
    // A keyboard with no image set is not drawn at all: an input-only manual
    // and most pedalboards are like this, and Hauptwerk does not draw them
    // either.
    const Id keySetId = kb.keyImageSetFor(layout_);
    if (keySetId == 0 || kb.numKeys <= 0) continue;
    if (kb.displayPageId != pageId) continue;
    const auto ksIt = model.keyImageSets.find(keySetId);
    if (ksIt == model.keyImageSets.end()) continue;
    if (!alreadyDrawn
             .insert({keySetId, kb.dispLeftFor(layout_), kb.dispTopFor(layout_),
                      kb.numKeys, kb.firstMidiNote})
             .second)
      continue;
    const KeyImageSet& ks = ksIt->second;
    // A drawn manual belongs to one of the organ's keyboards, so its keys must
    // arrive on that keyboard's channel rather than on a fixed one.
    const int channel = proc_.channelForKeyboard(kb.keyboardId);

    int x = kb.dispLeftFor(layout_);
    const int keyTop = kb.dispTopFor(layout_);
    for (int i = 0; i < kb.numKeys; ++i) {
      const int note = kb.firstMidiNote + i;
      const int pc = pitchClassOf(note);
      const Id shape = keyShapeFor(ks, pc, i == 0, i == kb.numKeys - 1);

      if (shape != 0) {
        const auto setIt = model.imageSets.find(shape);
        if (setIt != model.imageSets.end()) {
          KeyItem item;
          item.midiNote = note;
          item.channel = channel;
          item.imageSetId = shape;
          item.engagedIndex = ks.indexEngaged;
          item.disengagedIndex = ks.indexDisengaged;
          item.sharp = isSharpPitchClass(pc);
          // Key image sets normally declare no dimensions and let the bitmap
          // say. The images are tiny and cached, so asking is cheap, and the
          // answer is what makes a click land on the right key.
          int w = setIt->second.widthPx;
          int h = setIt->second.heightPx;
          if (w <= 0 || h <= 0) {
            if (const juce::Image* img = imageFor(shape, item.disengagedIndex)) {
              w = img->getWidth();
              h = img->getHeight();
            }
          }
          // No picture at all: the set names one of Hauptwerk's standard key
          // images, which that application ships and a sample set does not.
          // The manual is still fully described -- the spacings say how wide
          // a key is -- so draw it from those numbers rather than leaving a
          // hole where the keyboard should be.
          if (w <= 0 || h <= 0) {
            item.synthetic = true;
            const int unit = ks.spacingNaturalToNatural > 0
                                 ? ks.spacingNaturalToNatural
                                 : 12;
            if (item.sharp) {
              w = std::max(3, (unit * 11) / 20);
              h = unit * 3;
            } else {
              w = std::max(4, unit - 1);
              h = unit * 5;
            }
          }
          // Every key hangs from the same top edge; a sharp is simply a
          // shorter image, so it needs no vertical offset of its own.
          item.bounds = {x, keyTop, w > 0 ? w : 12, h > 0 ? h : 60};
          (item.sharp ? sharps : keys_).push_back(item);
        }
      }
      x += keyAdvance(ks, pc);
    }
  }

  keys_.insert(keys_.end(), sharps.begin(), sharps.end());
}

int ConsoleView::keyAt(juce::Point<int> p, int* outChannel) const {
  // Back to front: the sharps are last in the list and sit on top.
  for (auto it = keys_.rbegin(); it != keys_.rend(); ++it)
    if (it->bounds.contains(p)) {
      if (outChannel != nullptr) *outChannel = it->channel;
      return it->midiNote;
    }
  return -1;
}

juce::Rectangle<int> ConsoleView::keysBounds() const {
  juce::Rectangle<int> r;
  for (const auto& k : keys_) r = r.getUnion(k.bounds);
  return r;
}

void ConsoleView::timerCallback() {
  // MidiKeyboardState is what the engine already updates from the MIDI stream
  // every block, so a key lights up whether it was pressed on screen or on the
  // player's own console.
  uint64_t hash = 1469598103934665603ull;
  auto& state = proc_.keyboardState();
  for (const auto& k : keys_) {
    hash ^= state.isNoteOn(k.channel, k.midiNote) ? 1u : 0u;
    hash *= 1099511628211ull;
  }

  // The drawstops are watched the same way, and for the same reason: a stop
  // can change without anyone clicking it. A piston, a combination, the
  // sequencer or the command line all move the switch in the engine, and
  // repainting only on a mouse click leaves the jamb showing the registration
  // the player last set by hand rather than the one that is actually drawn.
  uint64_t stopHash = 1469598103934665603ull;
  for (const auto& item : items_) {
    if (item.switchId == 0 && item.controlId == 0) continue;
    stopHash ^= static_cast<uint64_t>(frameIndexFor(item));
    stopHash *= 1099511628211ull;
  }

  const bool keysMoved = hash != keyStateHash_;
  const bool stopsMoved = stopHash != stopStateHash_;
  keyStateHash_ = hash;
  stopStateHash_ = stopHash;

  // A stop changing means repainting the console furniture; a key changing
  // needs only the manuals, which is the common case and the cheap one.
  if (stopsMoved) repaint();
  else if (keysMoved) repaint(keysBounds());
}

juce::String ConsoleView::pageName(int index) const {
  if (index < 0 || index >= static_cast<int>(pageIds_.size())) return {};
  const auto& pages = proc_.organModel().displayPages;
  const auto it = pages.find(pageIds_[static_cast<size_t>(index)]);
  if (it == pages.end() || it->second.name.empty())
    return "Page " + juce::String(index + 1);
  return juce::String(it->second.name);
}

void ConsoleView::setLayout(int layout) {
  if (layout < 0 || layout == layout_) return;
  layout_ = layout;
  rebuild();
  repaint();
}

void ConsoleView::setPage(int index) {
  if (index < 0 || index >= static_cast<int>(pageIds_.size())) return;
  pageIndex_ = index;
  rebuild();
  repaint();
}

int ConsoleView::frameIndexFor(const Item& item) const {
  // A dragged control picks its frame from its position, off the staircase
  // the organ declares for its image set.
  if (item.controlId != 0) {
    const auto& stages = proc_.organModel().continuousControlStages;
    const auto it = stages.find(item.imageSetId);
    if (it == stages.end() || it->second.empty()) return item.defaultIndex;
    const int v = proc_.continuousControlValue(item.controlId);
    // First band whose top is at or above the value. Sorted ascending at
    // load, so this is the lowest band that still contains it.
    for (const auto& s : it->second)
      if (v <= s.highestValue) return s.imageIndex;
    // Above every declared band: the organ drew the top of the travel.
    return it->second.back().imageIndex;
  }

  if (item.switchId == 0) return item.defaultIndex;
  const bool on = proc_.switchEngaged(item.switchId);
  const int chosen = on ? item.engagedIndex : item.disengagedIndex;
  // A set that names no frame for a state falls back to what the instance
  // declares, rather than drawing nothing.
  return chosen > 0 ? chosen : item.defaultIndex;
}

const juce::Image* ConsoleView::imageFor(Id imageSetId, int index) {
  const int64_t key = cacheKey(imageSetId, index);
  const auto it = cache_.find(key);
  if (it != cache_.end())
    return it->second.isValid() ? &it->second : nullptr;

  const auto& model = proc_.organModel();
  const auto setIt = model.imageSets.find(imageSetId);
  if (setIt == model.imageSets.end()) {
    cache_[key] = juce::Image();
    return nullptr;
  }

  const ImageSet& set = setIt->second;
  const ImageSetElement* element = nullptr;
  for (const auto& el : set.elements)
    if (el.index == index) { element = &el; break; }
  // Some sets declare a single frame with no index; use it rather than fail.
  if (element == nullptr && !set.elements.empty() && index <= 1)
    element = &set.elements.front();

  if (element == nullptr || element->bitmapFile.empty()) {
    cache_[key] = juce::Image();
    return nullptr;
  }

  const auto path = standardComponent(
      resolveIgnoringCase(resolveBitmap(organRoot_, element->bitmapFile, set.packageId)),
      element->bitmapFile, set.packageId);
  juce::Image img = loadConsoleImage(juce::File(path.string()));

  // Hauptwerk predates transparent bitmaps: a set that ships BMPs carries a
  // separate mask image instead, black where the artwork shows and white where
  // the console behind it must show through. Without this a round drawstop is
  // drawn as the square it is stored as.
  if (img.isValid() && !set.transparencyMaskFile.empty()) {
    const auto maskPath = resolveIgnoringCase(
        resolveBitmap(organRoot_, set.transparencyMaskFile, set.packageId));
    juce::Image mask = loadConsoleImage(juce::File(maskPath.string()));
    if (mask.isValid()) {
      img = img.convertedToFormat(juce::Image::ARGB);
      const int w = std::min(img.getWidth(), mask.getWidth());
      const int h = std::min(img.getHeight(), mask.getHeight());
      juce::Image::BitmapData dst(img, juce::Image::BitmapData::readWrite);
      const juce::Image::BitmapData src(mask, juce::Image::BitmapData::readOnly);
      for (int y = 0; y < h; ++y) {
        for (int x = 0; x < w; ++x) {
          // Brightness, not one channel: masks are authored greyscale but not
          // always stored that way, and a colour cast must not shift the edge.
          const auto m = src.getPixelColour(x, y);
          const auto p = dst.getPixelColour(x, y);
          const float keep = 1.0f - m.getBrightness();
          dst.setPixelColour(x, y, p.withMultipliedAlpha(keep));
        }
      }
    }
  }

  // Wood the set expected from Hauptwerk's own components and could not find:
  // one of ours instead, drawn as a repeating fill, so the page keeps its
  // panels rather than showing black.
  if (!img.isValid() && set.packageId > 0 && set.packageId <= 10) {
    const std::string& name =
        element->bitmapFile.find_first_of("0123456789") != std::string::npos
            ? element->bitmapFile
            : set.name;
    if (juce::String(name).containsIgnoreCase("wood")) {
      img = woodTileFor(name);
      if (img.isValid()) generatedWood_.insert(imageSetId);
    }
  }

  cache_[key] = img; // a failed load is cached too, so it is not retried
  return img.isValid() ? &cache_[key] : nullptr;
}

std::filesystem::path ConsoleView::standardComponent(const std::filesystem::path& found,
                                                     const std::string& fileName,
                                                     Id packageId) const {
  std::error_code ec;
  if (packageId <= 0 || packageId > 10 || std::filesystem::exists(found, ec))
    return found;
  // A Hauptwerk installation keeps these packages beside its sample sets, and
  // the libraries the player has loaded from are remembered.
  for (const auto& lib : proc_.sampleLibraries()) {
    const auto candidate = resolveIgnoringCase(
        resolveBitmap(lib.getFullPathName().toStdString(), fileName, packageId));
    if (std::filesystem::exists(candidate, ec)) return candidate;
  }
  return found;
}

void ConsoleView::paint(juce::Graphics& g) {
  g.fillAll(juce::Colour(0xff0d0f12));

  if (!hasArtwork_) {
    g.setColour(juce::Colours::grey);
    g.drawText("This organ ships no console artwork on this page.",
               getLocalBounds(), juce::Justification::centred);
    return;
  }

  int drawn = 0, missing = 0;
  for (const auto& item : items_) {
    const juce::Image* img = imageFor(item.imageSetId, frameIndexFor(item));
    if (img == nullptr) {
      ++missing;
      // A control whose picture is not here still has to be seen and clicked.
      // Sets that build their control pages from "Hauptwerk Standard
      // Components" -- a package that ships with Hauptwerk, not with the set
      // -- write black labels meant to sit on light buttons. Without the
      // buttons that is black on black, and the page reads as empty. Draw a
      // plain one, lit when engaged, so the label and the state are legible.
      if (item.switchId != 0 && !item.tiled) {
        const bool on = frameIndexFor(item) == item.engagedIndex;
        const auto r = item.bounds.toFloat().reduced(1.0f);
        g.setColour(on ? juce::Colour(0xffe6cf7a) : juce::Colour(0xffc9c4b8));
        g.fillRoundedRectangle(r, 3.0f);
        g.setColour(juce::Colour(0xff5a5446));
        g.drawRoundedRectangle(r, 3.0f, 1.0f);
      }
      continue;
    }
    // Generated wood is a tile whatever the instance says, so it covers the
    // panel it stands in for rather than a 256-pixel square of it.
    if (item.tiled || generatedWood_.count(item.imageSetId) != 0) {
      // Repeat the tile across the declared rectangle. A backdrop authored as
      // an 85-pixel strip covers a 1536-wide page this way; drawing it once
      // leaves a sliver of artwork and bare background beside it.
      g.saveState();
      g.reduceClipRegion(item.bounds);
      g.setTiledImageFill(*img, item.bounds.getX(), item.bounds.getY(), 1.0f);
      g.fillRect(item.bounds);
      g.restoreState();
    } else {
      g.drawImageAt(*img, item.bounds.getX(), item.bounds.getY(), false);
    }
    ++drawn;
  }

  // Engraved text sits on the furniture it labels, so it is drawn after the
  // artwork and before the manuals.
  for (const auto& t : texts_) {
    g.setFont(t.font);
    g.setColour(t.colour);
    if (t.wrap)
      g.drawFittedText(t.text, t.bounds, t.justification, 8);
    else
      g.drawText(t.text, t.bounds, t.justification, false);
    ++drawn;
  }

  // The manuals go on top of the console furniture: a drawn manual is the one
  // thing on the page whose picture changes while the player is playing.
  auto& keyState = proc_.keyboardState();
  for (const auto& k : keys_) {
    const bool down = keyState.isNoteOn(k.channel, k.midiNote);
    const int frame = down ? k.engagedIndex : k.disengagedIndex;
    if (k.synthetic) {
      // Ivory and ebony, with the pressed key shaded rather than moved: the
      // set gives no travel, and a key that jumps would be a lie about it.
      const juce::Colour face =
          k.sharp ? juce::Colour(down ? 0xff454545 : 0xff1a1a1a)
                  : juce::Colour(down ? 0xffd8d2c2 : 0xfff2ece0);
      g.setColour(face);
      g.fillRect(k.bounds);
      g.setColour(juce::Colour(0xff2a2a2a));
      g.drawRect(k.bounds, 1);
      ++drawn;
      continue;
    }
    const juce::Image* img = imageFor(k.imageSetId, frame);
    // Fall back to the other frame rather than leaving a hole in the manual:
    // some sets ship only the released artwork.
    if (img == nullptr)
      img = imageFor(k.imageSetId, down ? k.disengagedIndex : k.engagedIndex);
    if (img == nullptr) continue;
    g.drawImageAt(*img, k.bounds.getX(), k.bounds.getY(), false);
    ++drawn;
  }

  // While learning, say which control is armed: an invisible mode is a trap.
  if (proc_.midiMap().learning()) {
    for (const auto& item : items_) {
      if (item.switchId != proc_.midiMap().learningTarget()) continue;
      g.setColour(juce::Colours::orange);
      g.drawRect(item.bounds, 3);
      break;
    }
  }

  // Say so rather than showing a mysteriously empty console: a set whose
  // images did not resolve looks identical to one that has none.
  if (drawn == 0 && missing > 0) {
    g.setColour(juce::Colours::orangered);
    g.drawText("Console artwork could not be loaded (" + juce::String(missing) +
                   " images). Check OrganInstallationPackages.",
               getLocalBounds().reduced(20), juce::Justification::centred);
  }
}

void ConsoleView::mouseDown(const juce::MouseEvent& e) {
  // A drawn manual is playable: clicking a key sounds it. The click goes
  // through MidiKeyboardState, which is the same path a physical console
  // takes, so stops and couplers apply to it identically.
  if (!e.mods.isPopupMenu()) {
    int channel = 1;
    const int note = keyAt(e.getPosition(), &channel);
    if (note >= 0) {
      heldKey_ = note;
      heldChannel_ = channel;
      proc_.keyboardState().noteOn(channel, note, 0.8f);
      repaint(keysBounds());
      return;
    }
  }

  // Topmost first: the controls are painted last, so they are hit first.
  for (auto it = items_.rbegin(); it != items_.rend(); ++it) {
    if (!it->clickable) continue;
    if (it->switchId == 0 && it->controlId == 0) continue;
    if (!it->hitBounds.contains(e.getPosition())) continue;

    if (e.mods.isPopupMenu()) {
      if (it->switchId != 0) showMidiMenu(it->switchId, it->bounds);
      return;
    }

    // A shoe or slider. The press only takes hold of it — the value does not
    // move until the mouse does, which is what "click it, hold, and drag"
    // means and what stops a stray click from throwing a setting across its
    // range.
    if (it->controlId != 0) {
      heldControl_ = it->controlId;
      heldControlBounds_ = it->hitBounds;
      heldControlHigherIsMore_ = it->controlHigherIsMore;
      heldControlStartY_ = e.getPosition().getY();
      heldControlStartValue_ = proc_.continuousControlValue(it->controlId);
      return;
    }

    proc_.setSwitchEngaged(it->switchId, !proc_.switchEngaged(it->switchId));
    repaint(it->bounds);
    return;
  }

  // A right-click on nothing cancels an armed learn, so an accidental arm is
  // easy to back out of.
  if (e.mods.isPopupMenu() && proc_.midiMap().learning()) {
    proc_.midiMap().cancelLearn();
    repaint();
  }
}

void ConsoleView::showMidiMenu(Id switchId, juce::Rectangle<int> bounds) {
  // Right-click a drawstop to map it. One message that flips it is what most
  // consoles send, but plenty send a separate message to draw and to cancel,
  // and a piston is held rather than latched — so the behaviour is offered
  // rather than assumed. The list is GrandOrgue's, which documents these
  // properly; Hauptwerk detects most of it for you and publishes no
  // equivalent set to copy.
  auto& map = proc_.midiMap();
  juce::PopupMenu menu;

  const auto existing = map.bindingsFor(MidiTargetKind::Switch, switchId);
  if (existing.empty()) {
    menu.addSectionHeader("Not mapped");
  } else {
    for (const MidiBinding* b : existing) {
      juce::String what =
          b->source.kind == MidiSourceKind::Note ? "Note " : "CC ";
      what << b->source.number;
      if (b->source.channel > 0) what << " ch " << b->source.channel;
      switch (b->trigger) {
        case MidiTrigger::Momentary: what << "  (held)"; break;
        case MidiTrigger::EngageOnly: what << "  (draws)"; break;
        case MidiTrigger::DisengageOnly: what << "  (cancels)"; break;
        case MidiTrigger::Toggle: what << "  (toggles)"; break;
      }
      menu.addSectionHeader(what);
    }
  }
  menu.addSeparator();
  menu.addItem(1, "Learn: toggle");
  menu.addItem(2, "Learn: held while pressed");
  menu.addItem(3, "Learn: draws it only");
  menu.addItem(4, "Learn: cancels it only");
  menu.addSeparator();
  menu.addItem(5, "Clear mapping", !existing.empty());

  menu.showMenuAsync(
      juce::PopupMenu::Options().withTargetComponent(this).withTargetScreenArea(
          localAreaToGlobal(bounds)),
      [this, switchId, bounds](int choice) {
        auto& m = proc_.midiMap();
        switch (choice) {
          case 1:
            m.beginLearnAs(MidiTargetKind::Switch, switchId, MidiTrigger::Toggle);
            break;
          case 2:
            m.beginLearnAs(MidiTargetKind::Switch, switchId,
                           MidiTrigger::Momentary);
            break;
          case 3:
            m.beginLearnAs(MidiTargetKind::Switch, switchId,
                           MidiTrigger::EngageOnly);
            break;
          case 4:
            m.beginLearnAs(MidiTargetKind::Switch, switchId,
                           MidiTrigger::DisengageOnly);
            break;
          case 5:
            m.unbindTarget(MidiTargetKind::Switch, switchId);
            proc_.saveMidiMap();
            break;
          default:
            return;
        }
        repaint(bounds);
      });
}

void ConsoleView::setControlFromMouse(juce::Point<int> p) {
  if (heldControl_ == 0) return;

  // Vertical, always, and RELATIVE to where the value already was.
  //
  // Nancy prints the rule on its own settings page: "To change numeric value
  // click it with mouse, hold mouse buton and drag up and down." So the axis
  // is up/down even for a control drawn 208 wide and 61 tall — the image's
  // shape says nothing about it, and `ClickingHigherIncreasesValue` was the
  // clue, since "higher" is a vertical word.
  //
  // Relative matters as much as the axis. Mapping the pointer's absolute
  // position onto the image would jump the value the instant it was clicked,
  // and across a 61-pixel image with 101 frames it would move two steps per
  // pixel. Starting from the value in hand is both what the organ describes
  // and what can actually be aimed.
  const int dy = heldControlStartY_ - p.getY(); // up is positive
  const double perPixel = heldControlHigherIsMore_ ? 0.5 : -0.5;
  const int v = juce::jlimit(
      0, 127, heldControlStartValue_ + juce::roundToInt(dy * perPixel));

  if (v == proc_.continuousControlValue(heldControl_)) return;
  proc_.setContinuousControl(heldControl_, v);
  repaint(heldControlBounds_);
}

void ConsoleView::mouseDrag(const juce::MouseEvent& e) {
  if (heldControl_ != 0) {
    // Deliberately not clamped to the image: a hand that slides off the side
    // of a shoe while pushing it is still pushing it, and the position
    // saturates at the end of the travel rather than jumping.
    setControlFromMouse(e.getPosition());
    return;
  }
  if (heldKey_ < 0) return;
  // Sliding along the manual plays it, the way a hand does. Dragging from one
  // manual onto another switches channel with the key, which is what actually
  // happens when a hand crosses between them.
  int channel = heldChannel_;
  const int note = keyAt(e.getPosition(), &channel);
  if (note == heldKey_ && channel == heldChannel_) return;
  proc_.keyboardState().noteOff(heldChannel_, heldKey_, 0.0f);
  heldKey_ = note;
  heldChannel_ = channel;
  if (note >= 0) proc_.keyboardState().noteOn(channel, note, 0.8f);
  repaint(keysBounds());
}

void ConsoleView::mouseUp(const juce::MouseEvent&) {
  heldControl_ = 0;
  if (heldKey_ < 0) return;
  proc_.keyboardState().noteOff(heldChannel_, heldKey_, 0.0f);
  heldKey_ = -1;
  repaint(keysBounds());
}

void ConsoleView::resized() {}

} // namespace mp::ui
